import os

#Import Balena API keys
BALENA_SUPERVISOR_API_KEY = os.environ['BALENA_SUPERVISOR_API_KEY']
BALENA_SUPERVISOR_ADDRESS = os.environ['BALENA_SUPERVISOR_ADDRESS']
BALENA_DEVICE_UUID = os.environ['BALENA_DEVICE_UUID']