version: '2.1'

services:
    controller:
        build: ./controller
        network_mode: "host"
        labels:
            io.balena.features.dbus: '1'
            io.balena.features.supervisor-api: '1'
        cap_add:
            - NET_ADMIN
        environment:
            DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"